wig_tab_sources = files(
    'wig-auth-dialog.c',
    'wig-crash-page.c',
    'wig-modal-dialog.c',
    'wig-script-dialog.c',
    'wig-tab-bar.c',
    'wig-tab-context-menu.c',
    'wig-tab-list-view.c',
    'wig-tab-list.c',
    'wig-tab-sidebar.c',
    'wig-tab-strip-layout.c',
    'wig-tab-widget.c',
    'wig-tab-wrap-layout.c',
    'wig-tab.c',
    'wig-tls-error-page.c',
)
