shared_module(
    'wig-web-process-extension',
    sources: files('wig-web-process-extension.c'),
    dependencies: [wpe_web_process_extension_dep],
    include_directories: ['.'],
    c_args: ['-DG_LOG_DOMAIN="wig-web-process-extension"'],
    install: true,
    install_dir: wig_web_process_extensions_dir,
)
